Repository ibhavikmakwana/Manch, pull requests merged in 2021-07, with the labels that each got.

#3 Update profile
  lib/main.dart
  lib/models/user_profile.dart
  lib/screen/dashboard/dashboard.dart
  lib/screen/dashboard/profile/edit_profile.dart
  lib/screen/dashboard/profile/profile_screen.dart
  lib/screen/dashboard/profile/store/profile_screen_store.dart
  lib/screen/dashboard/profile/view_profile.dart
  lib/values/app_colors.dart
  lib/values/app_constant.dart
  lib/values/theme.dart
  lib/widget/base_widget_switcher.dart
  lib/widget/indicator_dot.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#14 Upload user avatar feature and linting rules
  analysis_options.yaml
  android/app/src/main/AndroidManifest.xml
  lib/configure_main_app.dart
  lib/core/supabase/build_config.dart
  lib/generated/intl/messages_all.dart
  lib/main.dart
  lib/main_store.dart
  lib/models/user_profile.dart
  lib/route_generator.dart
  lib/screen/dashboard/dashboard.dart
  lib/screen/dashboard/home/home_screen.dart
  lib/screen/dashboard/profile/edit_profile.dart
  lib/screen/dashboard/profile/store/profile_screen_store.dart
  lib/screen/dashboard/profile/view_profile.dart
  lib/screen/dashboard/profile/widget/image_picker_options_dialog.dart
  lib/screen/dashboard/store/dashboard_store.dart
  lib/screen/onboarding/login_sign_up_screen.dart
  lib/screen/onboarding/splash_screen.dart
  lib/screen/onboarding/store/on_boarding_store.dart
  lib/values/theme.dart
  lib/widget/base_widget_switcher.dart
  lib/widget/custom_button.dart
  lib/widget/custom_text_field.dart
  lib/widget/network_cache_images.dart
  pubspec.lock
  pubspec.yaml
Labels: code quality, enhancement

#16 Allow user to update the existing user avatar
  lib/screen/dashboard/profile/profile_screen.dart
  lib/screen/dashboard/profile/store/profile_screen_store.dart
Labels: enhancement

#19 Add launcher app icons and splash screen UI with icon.
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  assets/img/launcher.png
  assets/svg/logo.svg
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  lib/screen/onboarding/splash_screen.dart
  lib/values/assets.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#20 Fixed update profile not happening due to in valid validation check.
  lib/screen/dashboard/profile/store/profile_screen_store.dart
  lib/widget/network_cache_images.dart
  pubspec.lock
Labels: bug

#24 Show proper validation messages and snack bar for the errors
  lib/screen/dashboard/profile/edit_profile.dart
  lib/screen/dashboard/profile/store/profile_screen_store.dart
  lib/screen/onboarding/login_sign_up_screen.dart
  lib/screen/onboarding/store/on_boarding_store.dart
  lib/values/extensions.dart
  lib/widget/custom_text_field.dart
Labels: enhancement

#25 Update README.md
  README.md
Labels: documentation
